### ISSUE TITLE
Please create a docker compose file to run it

### ISSUE THREAD

**Issue by tascape** [gigsterous/auth-server#3]

**Comment by svachmic** [comment]
Hi @tascape, thanks for reaching out! I unfortunately fail to see why docker compose would be helpful here as the auth-server has only one component. Also docker compose can be different for other developers and if we provided one, it would get in their way. 

The repo has a Dockerfile, so you should be able to include it in any of your deployments of choice (compose, kubernetes...).

Feel free to comment with more details!

**Comment by svachmic** [comment]
Hey, it has been 7 days with no response. Due to inactivity/lack of information, I am closing this issue. Feel free to reach out with more details and we can reopen the issue.
