### ISSUE TITLE
Scalable ?

### ISSUE THREAD

**Issue by ikishor99** [gigsterous/auth-server#4]
What if I scale this to N insatnces in cloud ?

**Comment by Smedzlatko** [comment]
Hi, @ikishor.

You can scale this auth server quite easily. The only thing you need to do is to connect it to a real standalone database. This example, as is, uses H2 in-memory database so each instance would have its own copy. You can change the configuration and datasource in `application.properties`.

Once you have done that, you can spin as many instances as you wish.
